import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>SMS Spoof</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className="bg-white px-10">
        <section className="  rounded-md shadow-md h-12 my-5 py-10">
            <h1>Nav here</h1>
        </section>
        <section className="h-24 text-center my-10">
            <h1 className="text-5xl text-teal-600 font-medium">Hero here</h1>
        </section>
        <section className="shadow-lg rounded-xl h-80 text-center max-w-md my-22 mx-auto py-10">
            <h1 className="text-3xl text-indigo-600 font-medium">input form here</h1>
        </section>
      </main>
    </div>
  )
}
